# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x07student\"0\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\t\"9\n\x14\x43reateStudentRequest\x12!\n\x07student\x18\x01 \x01(\x0b\x32\x10.student.Student\"(\n\x15\x43reateStudentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x12ReadStudentRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x13ReadStudentResponse\x12!\n\x07student\x18\x01 \x01(\x0b\x32\x10.student.Student\"=\n\x14UpdateStudentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\t\"(\n\x15UpdateStudentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x14\x44\x65leteStudentRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x15\x44\x65leteStudentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12ListStudentRequest\"9\n\x13ListStudentResponse\x12\"\n\x08students\x18\x01 \x03(\x0b\x32\x10.student.Student2\x9e\x03\n\x0eStudentService\x12P\n\rCreateStudent\x12\x1d.student.CreateStudentRequest\x1a\x1e.student.CreateStudentResponse\"\x00\x12J\n\x0bReadStudent\x12\x1b.student.ReadStudentRequest\x1a\x1c.student.ReadStudentResponse\"\x00\x12P\n\rUpdateStudent\x12\x1d.student.UpdateStudentRequest\x1a\x1e.student.UpdateStudentResponse\"\x00\x12P\n\rDeleteStudent\x12\x1d.student.DeleteStudentRequest\x1a\x1e.student.DeleteStudentResponse\"\x00\x12J\n\x0bListStudent\x12\x1b.student.ListStudentRequest\x1a\x1c.student.ListStudentResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STUDENT._serialized_start=26
  _STUDENT._serialized_end=74
  _CREATESTUDENTREQUEST._serialized_start=76
  _CREATESTUDENTREQUEST._serialized_end=133
  _CREATESTUDENTRESPONSE._serialized_start=135
  _CREATESTUDENTRESPONSE._serialized_end=175
  _READSTUDENTREQUEST._serialized_start=177
  _READSTUDENTREQUEST._serialized_end=209
  _READSTUDENTRESPONSE._serialized_start=211
  _READSTUDENTRESPONSE._serialized_end=267
  _UPDATESTUDENTREQUEST._serialized_start=269
  _UPDATESTUDENTREQUEST._serialized_end=330
  _UPDATESTUDENTRESPONSE._serialized_start=332
  _UPDATESTUDENTRESPONSE._serialized_end=372
  _DELETESTUDENTREQUEST._serialized_start=374
  _DELETESTUDENTREQUEST._serialized_end=408
  _DELETESTUDENTRESPONSE._serialized_start=410
  _DELETESTUDENTRESPONSE._serialized_end=450
  _LISTSTUDENTREQUEST._serialized_start=452
  _LISTSTUDENTREQUEST._serialized_end=472
  _LISTSTUDENTRESPONSE._serialized_start=474
  _LISTSTUDENTRESPONSE._serialized_end=531
  _STUDENTSERVICE._serialized_start=534
  _STUDENTSERVICE._serialized_end=948
# @@protoc_insertion_point(module_scope)
