# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x11\x43reateUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"-\n\x11UpdateUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xd3\x01\n\x0bUserService\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.User\x12\x31\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\n.user.User\x12\x31\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\n.user.User\x12\x31\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\n.user.Userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=20
  _USER._serialized_end=85
  _GETUSERREQUEST._serialized_start=87
  _GETUSERREQUEST._serialized_end=115
  _CREATEUSERREQUEST._serialized_start=117
  _CREATEUSERREQUEST._serialized_end=162
  _UPDATEUSERREQUEST._serialized_start=164
  _UPDATEUSERREQUEST._serialized_end=209
  _DELETEUSERREQUEST._serialized_start=211
  _DELETEUSERREQUEST._serialized_end=242
  _USERSERVICE._serialized_start=245
  _USERSERVICE._serialized_end=456
# @@protoc_insertion_point(module_scope)
